services:
  verticalslicesample.api:
    image: ${DOCKER_REGISTRY-}verticalslicesampleapi
    container_name: verticalslicesample.api
    build:
      context: .
      dockerfile: src/VerticalSliceSample.Api/Dockerfile
    ports:
      - "5000:5000" 
      - "5001:5001"

  verticalslicesample.database:
    image: postgres:18-alpine
    container_name: verticalslicesample.database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sampledb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  verticalslicesample.pgadmin:
    image: dpage/pgadmin4:latest
    container_name: verticalslicesample.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5450:80"
    depends_on:
      - verticalslicesample.database
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local